# Generated by Django 2.0.2 on 2018-02-28 14:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0003_auto_20180227_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='message',
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_prof',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Student'), (1, 'Professor')], default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='moodle.Course'),
        ),
    ]
