# Generated by Django 2.0.2 on 2018-02-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0004_auto_20180228_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
    ]
